import type { Restaurant, MenuItem, Review } from "./types"

export const restaurants: Restaurant[] = [
  {
    id: "le-bernardin",
    name: "Le Bernardin",
    description: "Exquisite French seafood cuisine in an elegant setting",
    cuisine: ["French", "Seafood", "Fine Dining"],
    priceRange: "$$$$",
    rating: 4.8,
    reviewCount: 2847,
    image: "/placeholder.svg?height=400&width=600&query=elegant french restaurant interior",
    images: [
      "/placeholder.svg?height=400&width=600&query=elegant french restaurant interior",
      "/placeholder.svg?height=400&width=600&query=fine dining restaurant ambiance",
      "/placeholder.svg?height=400&width=600&query=luxury restaurant private dining",
    ],
    address: "155 West 51st Street, New York, NY 10019",
    phone: "+1 (212) 554-1515",
    email: "reservations@le-bernardin.com",
    coordinates: { lat: 40.7614, lng: -73.9776 },
    hours: {
      monday: { open: "17:30", close: "22:00" },
      tuesday: { open: "17:30", close: "22:00" },
      wednesday: { open: "17:30", close: "22:00" },
      thursday: { open: "17:30", close: "22:00" },
      friday: { open: "17:30", close: "22:30" },
      saturday: { open: "17:30", close: "22:30" },
      sunday: { closed: true },
    },
    features: ["Michelin Star", "Wine Pairing", "Private Dining", "Valet Parking"],
    dressCode: "Business Casual to Formal",
    reservationPolicy: "Reservations required. 24-hour cancellation policy.",
    cancellationPolicy: "Cancellations must be made at least 24 hours in advance to avoid charges.",
  },
  {
    id: "sakura-omakase",
    name: "Sakura Omakase",
    description: "Authentic Japanese omakase experience with the finest ingredients",
    cuisine: ["Japanese", "Sushi", "Omakase"],
    priceRange: "$$$$",
    rating: 4.9,
    reviewCount: 1523,
    image: "/placeholder.svg?height=400&width=600&query=japanese omakase sushi counter",
    images: [
      "/placeholder.svg?height=400&width=600&query=japanese omakase sushi counter",
      "/placeholder.svg?height=400&width=600&query=traditional japanese restaurant interior",
      "/placeholder.svg?height=400&width=600&query=sushi chef preparing omakase",
    ],
    address: "2891 Mission Street, San Francisco, CA 94110",
    phone: "+1 (415) 282-8283",
    email: "info@sakura-omakase.com",
    coordinates: { lat: 37.7749, lng: -122.4194 },
    hours: {
      monday: { closed: true },
      tuesday: { open: "18:00", close: "22:00" },
      wednesday: { open: "18:00", close: "22:00" },
      thursday: { open: "18:00", close: "22:00" },
      friday: { open: "18:00", close: "22:30" },
      saturday: { open: "18:00", close: "22:30" },
      sunday: { open: "18:00", close: "21:30" },
    },
    features: ["Omakase Only", "Counter Seating", "Sake Pairing", "Seasonal Menu"],
    dressCode: "Smart Casual",
    reservationPolicy: "Advance reservations required. Limited seating available.",
    cancellationPolicy: "48-hour cancellation policy. Late cancellations subject to full charge.",
  },
]

export const menuItems: MenuItem[] = [
  {
    id: "lobster-thermidor",
    name: "Lobster Thermidor",
    description: "Classic French lobster dish with cognac cream sauce",
    detailedDescription:
      "Fresh Maine lobster tail, delicately poached and served in its shell with a rich cognac cream sauce, finished with Gruyère cheese and fresh herbs. A timeless French classic that exemplifies our commitment to traditional techniques and premium ingredients.",
    price: 68.0,
    image: "/placeholder.svg?height=300&width=400&query=lobster thermidor fine dining",
    images: [
      "/placeholder.svg?height=300&width=400&query=lobster thermidor fine dining",
      "/placeholder.svg?height=300&width=400&query=lobster thermidor preparation",
      "/placeholder.svg?height=300&width=400&query=lobster thermidor plated elegantly",
    ],
    category: "Seafood",
    ingredients: ["Maine Lobster", "Cognac", "Heavy Cream", "Gruyère Cheese", "Shallots", "Fresh Thyme", "White Wine"],
    allergens: ["Shellfish", "Dairy", "Alcohol"],
    nutritionalInfo: {
      calories: 485,
      protein: 42,
      carbs: 8,
      fat: 28,
    },
    preparationTime: 25,
    rating: 4.9,
    reviewCount: 234,
    chef: "Chef Antoine Dubois",
    restaurantId: "le-bernardin",
    isBestSeller: true,
  },
  {
    id: "wagyu-beef-tenderloin",
    name: "A5 Wagyu Beef Tenderloin",
    description: "Premium Japanese Wagyu with seasonal vegetables",
    detailedDescription:
      "Authentic A5 grade Japanese Wagyu beef tenderloin, grilled to perfection and served with roasted seasonal vegetables, truffle jus, and microgreens. This exceptional cut represents the pinnacle of beef quality and marbling.",
    price: 125.0,
    image: "/placeholder.svg?height=300&width=400&query=wagyu beef tenderloin fine dining",
    images: [
      "/placeholder.svg?height=300&width=400&query=wagyu beef tenderloin fine dining",
      "/placeholder.svg?height=300&width=400&query=wagyu beef raw marbling",
      "/placeholder.svg?height=300&width=400&query=wagyu beef plated with vegetables",
    ],
    category: "Meat",
    ingredients: ["A5 Wagyu Beef", "Seasonal Vegetables", "Black Truffle", "Red Wine Jus", "Microgreens", "Sea Salt"],
    allergens: ["None"],
    nutritionalInfo: {
      calories: 620,
      protein: 48,
      carbs: 12,
      fat: 42,
    },
    preparationTime: 20,
    rating: 4.8,
    reviewCount: 189,
    chef: "Chef Marcus Johnson",
    restaurantId: "le-bernardin",
    isBestSeller: true,
  },
  {
    id: "omakase-tasting",
    name: "Chef's Omakase Experience",
    description: "15-course tasting menu featuring seasonal selections",
    detailedDescription:
      "An intimate culinary journey featuring 15 carefully crafted courses that showcase the finest seasonal ingredients. Each dish is personally selected and prepared by our head chef, offering a unique dining experience that changes with the seasons.",
    price: 185.0,
    image: "/placeholder.svg?height=300&width=400&query=omakase sushi tasting menu",
    images: [
      "/placeholder.svg?height=300&width=400&query=omakase sushi tasting menu",
      "/placeholder.svg?height=300&width=400&query=sushi chef preparing omakase",
      "/placeholder.svg?height=300&width=400&query=omakase course presentation",
    ],
    category: "Tasting Menu",
    ingredients: ["Seasonal Fish", "Premium Rice", "Wasabi", "Soy Sauce", "Seasonal Vegetables", "Specialty Items"],
    allergens: ["Fish", "Soy", "Sesame"],
    nutritionalInfo: {
      calories: 850,
      protein: 65,
      carbs: 45,
      fat: 35,
    },
    preparationTime: 120,
    rating: 4.9,
    reviewCount: 456,
    chef: "Chef Hiroshi Tanaka",
    restaurantId: "sakura-omakase",
    isBestSeller: true,
  },
  {
    id: "truffle-risotto",
    name: "Black Truffle Risotto",
    description: "Creamy Arborio rice with fresh black truffles",
    detailedDescription:
      "Luxurious Arborio rice slowly cooked to creamy perfection with Parmigiano-Reggiano, finished with generous shavings of fresh black Périgord truffles and a touch of white truffle oil. A celebration of one of nature's most prized ingredients.",
    price: 48.0,
    originalPrice: 55.0,
    image: "/placeholder.svg?height=300&width=400&query=black truffle risotto fine dining",
    images: [
      "/placeholder.svg?height=300&width=400&query=black truffle risotto fine dining",
      "/placeholder.svg?height=300&width=400&query=truffle shaving on risotto",
      "/placeholder.svg?height=300&width=400&query=creamy risotto preparation",
    ],
    category: "Pasta & Risotto",
    ingredients: [
      "Arborio Rice",
      "Black Truffles",
      "Parmigiano-Reggiano",
      "White Wine",
      "Vegetable Stock",
      "Butter",
      "Onions",
    ],
    allergens: ["Dairy", "Alcohol"],
    nutritionalInfo: {
      calories: 420,
      protein: 18,
      carbs: 52,
      fat: 16,
    },
    preparationTime: 30,
    rating: 4.7,
    reviewCount: 312,
    chef: "Chef Isabella Romano",
    restaurantId: "le-bernardin",
    isPromotion: true,
    promotionType: "fixed",
    promotionValue: 7,
    isVegetarian: true,
  },
  {
    id: "tasting-menu-duo",
    name: "Romantic Tasting Menu for Two",
    description: "Perfect for special occasions and intimate dining",
    detailedDescription:
      "A carefully curated 8-course tasting menu designed for two, featuring our signature dishes and wine pairings. Each course is designed to be shared, creating an intimate and memorable dining experience perfect for anniversaries, proposals, or special celebrations.",
    price: 295.0,
    originalPrice: 340.0,
    image: "/placeholder.svg?height=300&width=400&query=romantic dinner for two fine dining",
    images: [
      "/placeholder.svg?height=300&width=400&query=romantic dinner for two fine dining",
      "/placeholder.svg?height=300&width=400&query=tasting menu courses plated",
      "/placeholder.svg?height=300&width=400&query=wine pairing with dinner",
    ],
    category: "Tasting Menu",
    isCombo: true,
    comboItems: [
      { name: "Amuse-Bouche Selection", quantity: 2, id: "amuse-bouche" },
      { name: "Lobster Thermidor", quantity: 1, id: "lobster-thermidor" },
      { name: "Wagyu Beef Tenderloin", quantity: 1, id: "wagyu-beef-tenderloin" },
      { name: "Dessert Tasting", quantity: 2, id: "dessert-tasting" },
    ],
    ingredients: ["Various Premium Ingredients", "Wine Pairings", "Seasonal Selections"],
    allergens: ["Shellfish", "Dairy", "Alcohol", "Gluten"],
    nutritionalInfo: {
      calories: 1250,
      protein: 85,
      carbs: 65,
      fat: 58,
    },
    preparationTime: 150,
    rating: 4.9,
    reviewCount: 89,
    chef: "Chef Antoine Dubois",
    restaurantId: "le-bernardin",
    isPromotion: true,
    promotionType: "fixed",
    promotionValue: 45,
  },
]

export const reviews: Review[] = [
  {
    id: "1",
    userId: "user1",
    userName: "Sarah M.",
    userAvatar: "/placeholder.svg?height=40&width=40&query=professional woman avatar",
    rating: 5,
    comment:
      "Absolutely exceptional dining experience. The lobster thermidor was perfectly executed, and the service was impeccable. Worth every penny for a special occasion.",
    date: "2024-01-15",
    helpful: 23,
  },
  {
    id: "2",
    userId: "user2",
    userName: "Michael R.",
    userAvatar: "/placeholder.svg?height=40&width=40&query=professional man avatar",
    rating: 5,
    comment:
      "The omakase experience was transcendent. Chef Tanaka's attention to detail and the quality of ingredients were outstanding. A true culinary journey.",
    date: "2024-01-12",
    helpful: 18,
  },
  {
    id: "3",
    userId: "user3",
    userName: "Emily L.",
    userAvatar: "/placeholder.svg?height=40&width=40&query=young woman avatar",
    rating: 4,
    comment:
      "Beautiful presentation and flavors. The truffle risotto was rich and indulgent. Atmosphere is perfect for a romantic dinner.",
    date: "2024-01-10",
    helpful: 12,
  },
]

export const categories = ["All", "Seafood", "Meat", "Pasta & Risotto", "Tasting Menu", "Appetizers", "Desserts"]

export const quickNotes = [
  "No onions",
  "Extra spicy",
  "On the side",
  "Well done",
  "Medium rare",
  "No cheese",
  "Extra sauce",
  "Gluten free",
  "Vegetarian",
  "Less salt",
  "Allergy: Nuts",
  "Allergy: Shellfish",
  "Extra hot",
  "Light preparation",
]
